### PR TITLE
fix: signal.Notify usage

### PR DESCRIPTION
**Pull request by pellared**
## Why

1. [`signal.Notify`](https://pkg.go.dev/os/signal#Notify) should be used with a buffered channel

> Package signal will not block sending to c: the caller must ensure that c has sufficient buffer space to keep up with the expected signal rate. For a channel used for notification of just one signal value, a buffer of size 1 is sufficient.

2. Opportunistic improvement: use a buffered `errChan` so that the goroutine could finish sooner.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by pellared** [comment]
@aeneasr PTAL

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
The CI is failing for some reason, can you PTAL?

**Comment by pellared** [comment]
> The CI is failing for some reason, can you PTAL?

@aeneasr What do you mean by CI? Everything is passing on GitHub and I am not sure if I have access to Travis CI.

The only failing build I see is [this one](https://github.com/ory/graceful/actions/runs/3269196771/jobs/5376443283) which was introduced in the `master` branch recently.

**Comment by aeneasr** [comment]
Looks like it was an issue with the PR linter :) It's green now!

**Comment by aeneasr** [comment]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Pull request merged**
